version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - gocritic
    - copyloopvar
    - gochecknoinits
    - gosec
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - performance
        - style
        - experimental
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: UK

formatters:
  enable:
    - gofmt
    - goimports
